# Generated by Django 2.0.3 on 2019-07-24 22:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('orders', '0002_auto_20190723_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
