# Generated by Django 2.0.3 on 2019-07-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190724_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='style',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
