# Generated by Django 2.0.3 on 2019-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190724_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_order',
            name='price',
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
