# Generated by Django 2.0.3 on 2019-07-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190725_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='size',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_order',
            name='extra_green_peppers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_order',
            name='extra_muchrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_order',
            name='extra_onions',
            field=models.BooleanField(default=False),
        ),
    ]
