# Generated by Django 2.0.3 on 2019-08-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190725_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['style']},
        ),
        migrations.AddField(
            model_name='order',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_order',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
