# Generated by Django 2.0.3 on 2019-08-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190808_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinner_platters',
        ),
        migrations.AddField(
            model_name='order',
            name='dinner_platters',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Dinner_Platter'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Pasta'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_orders',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza_Order'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Salad'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='sub_orders',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Sub_Order'),
            preserve_default=False,
        ),
    ]
