# Generated by Django 2.0.3 on 2019-08-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190808_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinner_platters',
        ),
        migrations.AddField(
            model_name='order',
            name='dinner_platters',
            field=models.ManyToManyField(blank=True, to='orders.Dinner_Platter'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_orders',
            field=models.ManyToManyField(blank=True, to='orders.Pizza_Order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='sub_orders',
            field=models.ManyToManyField(blank=True, to='orders.Sub_Order'),
        ),
    ]
