# Generated by Django 2.0.3 on 2019-08-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190808_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinner_platters',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pastas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza_orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_orders',
        ),
        migrations.DeleteModel(
            name='Dinner_Platter',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
