# Generated by Django 2.0.3 on 2019-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190808_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_platter', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('user', models.CharField(max_length=64)),
                ('final', models.BooleanField(default=False)),
                ('dinner_platters', models.ManyToManyField(blank=True, to='orders.Dinner_Platter')),
                ('pastas', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizza_orders', models.ManyToManyField(blank=True, to='orders.Pizza_Order')),
                ('salads', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('sub_orders', models.ManyToManyField(blank=True, to='orders.Sub_Order')),
            ],
        ),
    ]
